esphome:
  name: cabina_flujo_laminar
  friendly_name: Cabina_flujo_laminar

 
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ic9el12GrvOWl3Eg+deM3SWL7v3yF8sWNBsxP5kRbeE="
  reboot_timeout: 0s


ota:
- platform: esphome
  password: "771f1a8737d27adcdb16e9f860520fc8"


wifi:
  networks:
    - ssid: Alejandria_rpt_2.4GHz
      password: Qwertyuiop0987654321
      priority: 10   # Más prioridad
    - ssid: Mini_Alejandria
      password: Qwert54321
      priority: 5    # Menos prioridad
  reboot_timeout: 0s  # Desactiva el reinicio (o usa un valor mayor, ej. 1h)
  # Si no encuentra ninguna de las redes anteriores,
  # crea su propio AP (útil para emergencias).
 
  ap:
    ssid: "Cabina_flujo_laminar"
    password: "123456789"

captive_portal:


web_server:
  port: 80
  ota: true
  local: true




sensor:

# --- contador pulsos velocidad ventilador ---
  - platform: pulse_counter
    pin: 18
    name: "RPM Fan Aire Nuevo"
    id: RPM_aire_nuevo
    unit_of_measurement: "RPM"
    update_interval: 1s
    filters:
      - multiply: 0.60  # Si 2 pulsos por vuelta, 1s → 30 = RPM aproximado

    
